### ISSUE TITLE
remove install.packages() call from Rmd

### ISSUE THREAD

**Issue by maxheld83** [Char-XWW/whr#11]
there are some `install.packages()` calls in the source; these are superfluous.
It's enough to express dependencies in `DESCRIPTION`.

In particular, there should be no `usethis::use_package()` call in the source; just add the package to `DESCRIPTION` using this command *once*, and then you can `library("foo")` it.

**Comment by Char-XWW** [comment]
should be done now

**Comment by Char-XWW** [comment]
after I removed all packages from Index.Rmd, I cannot push anything, because it always tell me that I don't have package "foo"
![fehlermeldung11111111](https://user-images.githubusercontent.com/56732411/68598011-38a67b80-049e-11ea-8133-eb02a4dd7778.png)

**Comment by maxheld83** [comment]
I think this might be because your `DESCRIPTION` is invalid:

```
Imports: 
    plotly
    corrplot
    maps
    wildcard
    viridis
    dplyr
    install.packages("maps", repos = "http://cran.us.r-project.org")
    install.packages("wildcard", repos = "http://cran.us.r-project.org")
```

- the packages should be comma-separated
- `install.packages()` isn't valid in this context.

To make sure that your `DESCRIPTION` is valid, delete the whole `Imports: section`, and then (re-)run *locally* `usethis::use_package("foo")` for each of the packages; this will place the correct entries into your `DESCRIPTION`, which you can then commit.
