### ISSUE TITLE
find better plot for world happiness rankings

### ISSUE THREAD

**Issue by maxheld83** [Char-XWW/whr#7]
the current plot has the labels overplotted, so it's impossible to see which country is which.
I think this calls for another plot that avoids the overplotted labels.

**Comment by maxheld83** [comment]
there's probably no technical solution to this -- there are just too many countries to have them all on the y-axis.

**Comment by Char-XWW** [comment]
the idea is to use it interactively. because there are too many countries for single overview.


![Bildschirmfoto 2019-11-11 um 15 30 34](https://user-images.githubusercontent.com/56732411/68600180-54ac1c00-04a2-11ea-8b3f-c2ff8a15e5d7.png)

**Comment by maxheld83** [comment]
ok!
